### ISSUE TITLE
Whats the difference between this plugin and gi?

### ISSUE THREAD

**Issue by astier** [obcat/vim-ipos#2]

**Comment by obcat** [comment]
Hi, thank you for your question.

The difference is the start position of Insert mode.

For `gi`, the start position is the position where the cursor was placed when the last Insert was - started -.

OTOH, for `<Plug>(ipos-startinsert)` which this plugin provides, it is the position where the cursor was placed when the last Insert was - finished -.

Please feel free to let me know if you have more qustions.

**Comment by astier** [comment]
Thanks.
